
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadoress;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TD = 95;
  public static final int LEFT = 25;
  public static final int CIERRA_TEXT_AREA = 113;
  public static final int DIVISION = 99;
  public static final int MENOR_IGUAL = 59;
  public static final int MENOR_QUE = 58;
  public static final int PARENTESIS_ABRE = 89;
  public static final int COLUMN = 37;
  public static final int TYPE = 29;
  public static final int MODO = 75;
  public static final int ROWS = 34;
  public static final int CIERRA_C_H1 = 105;
  public static final int PARENTESIS_CIERRA = 90;
  public static final int ASC = 66;
  public static final int NAME = 32;
  public static final int ROW = 36;
  public static final int TEXTO = 20;
  public static final int INIT = 77;
  public static final int C_GCIC = 2;
  public static final int ALT = 41;
  public static final int TEXT_ALIGN = 24;
  public static final int LETIMPAR_NUM = 69;
  public static final int ALL = 22;
  public static final int NUMERO = 100;
  public static final int INTEGER = 48;
  public static final int MAYOR_QUE = 60;
  public static final int CORCHETE_ABRE = 91;
  public static final int C_LINK = 5;
  public static final int C_OPTION = 11;
  public static final int FALSE = 52;
  public static final int BACKGROUND = 18;
  public static final int NOT = 65;
  public static final int CENTER = 27;
  public static final int CIERRA_C_P = 109;
  public static final int THENWHILE = 86;
  public static final int C_SPAM = 7;
  public static final int THEN = 81;
  public static final int TIPOS_LETRA = 23;
  public static final int ABRE_C_H1 = 104;
  public static final int C_BODY = 6;
  public static final int WIDTH = 39;
  public static final int C_TEXTAREA = 9;
  public static final int REVERSE = 70;
  public static final int RGB_COLOR = 46;
  public static final int IGUALDAD = 55;
  public static final int CLASS = 35;
  public static final int ALERT_INFO = 73;
  public static final int C_DIV = 12;
  public static final int C_HEAD = 3;
  public static final int GETELEMENBYID = 76;
  public static final int NUM_ALEATORIO = 72;
  public static final int HUNTIL = 83;
  public static final int C_SCRIPTING = 43;
  public static final int C_INPUT = 8;
  public static final int CIERRA_INIT = 88;
  public static final int TRUE = 51;
  public static final int IGUAL = 56;
  public static final int ABRE_TEXT_AREA = 112;
  public static final int WHILE = 85;
  public static final int COLS = 33;
  public static final int DECIMAL = 49;
  public static final int CHAR = 53;
  public static final int BOOLEAN = 50;
  public static final int JUSTIFY = 28;
  public static final int ABRE_C_SPAM = 106;
  public static final int ELSE = 80;
  public static final int C_BR = 14;
  public static final int EOF = 0;
  public static final int SUMA = 96;
  public static final int ABRE_INPUT = 110;
  public static final int PROCESS_ = 44;
  public static final int REPEAT = 82;
  public static final int C_IMG = 13;
  public static final int ABRE_INIT = 87;
  public static final int DIFERENCIACION = 57;
  public static final int TEXTO_ID = 21;
  public static final int SRC = 38;
  public static final int HREF = 17;
  public static final int COMILLA = 93;
  public static final int OR = 63;
  public static final int EXIT = 74;
  public static final int error = 1;
  public static final int RESTA = 97;
  public static final int CIERRA_INPUT = 111;
  public static final int IF = 79;
  public static final int DESC = 67;
  public static final int ID = 31;
  public static final int COLOR = 16;
  public static final int ON_LOAD = 45;
  public static final int C_SELECT = 10;
  public static final int END = 78;
  public static final int C_H1 = 4;
  public static final int MULTIPLICACION = 98;
  public static final int TIPOS_DE_INPUT = 30;
  public static final int HEIGHT = 40;
  public static final int ABRE_C_P = 108;
  public static final int CARACTER_ALEATORIO = 71;
  public static final int FONT_FAMILY = 101;
  public static final int FONT_SIZE = 19;
  public static final int INSERT = 84;
  public static final int SIZE = 103;
  public static final int ALINEACION = 102;
  public static final int STRING = 54;
  public static final int ONCLICK = 42;
  public static final int CIERRA_C_SPAM = 107;
  public static final int CTE_COLOR = 47;
  public static final int AND = 64;
  public static final int C_BUTTON = 15;
  public static final int RIGH = 26;
  public static final int LETPAR_NUM = 68;
  public static final int CORCHETE_CIERRA = 92;
  public static final int MAYOR_IGUAL = 62;
  public static final int TI = 94;
  public static final int MAYOR_IGUAK = 61;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "C_GCIC",
  "C_HEAD",
  "C_H1",
  "C_LINK",
  "C_BODY",
  "C_SPAM",
  "C_INPUT",
  "C_TEXTAREA",
  "C_SELECT",
  "C_OPTION",
  "C_DIV",
  "C_IMG",
  "C_BR",
  "C_BUTTON",
  "COLOR",
  "HREF",
  "BACKGROUND",
  "FONT_SIZE",
  "TEXTO",
  "TEXTO_ID",
  "ALL",
  "TIPOS_LETRA",
  "TEXT_ALIGN",
  "LEFT",
  "RIGH",
  "CENTER",
  "JUSTIFY",
  "TYPE",
  "TIPOS_DE_INPUT",
  "ID",
  "NAME",
  "COLS",
  "ROWS",
  "CLASS",
  "ROW",
  "COLUMN",
  "SRC",
  "WIDTH",
  "HEIGHT",
  "ALT",
  "ONCLICK",
  "C_SCRIPTING",
  "PROCESS_",
  "ON_LOAD",
  "RGB_COLOR",
  "CTE_COLOR",
  "INTEGER",
  "DECIMAL",
  "BOOLEAN",
  "TRUE",
  "FALSE",
  "CHAR",
  "STRING",
  "IGUALDAD",
  "IGUAL",
  "DIFERENCIACION",
  "MENOR_QUE",
  "MENOR_IGUAL",
  "MAYOR_QUE",
  "MAYOR_IGUAK",
  "MAYOR_IGUAL",
  "OR",
  "AND",
  "NOT",
  "ASC",
  "DESC",
  "LETPAR_NUM",
  "LETIMPAR_NUM",
  "REVERSE",
  "CARACTER_ALEATORIO",
  "NUM_ALEATORIO",
  "ALERT_INFO",
  "EXIT",
  "MODO",
  "GETELEMENBYID",
  "INIT",
  "END",
  "IF",
  "ELSE",
  "THEN",
  "REPEAT",
  "HUNTIL",
  "INSERT",
  "WHILE",
  "THENWHILE",
  "ABRE_INIT",
  "CIERRA_INIT",
  "PARENTESIS_ABRE",
  "PARENTESIS_CIERRA",
  "CORCHETE_ABRE",
  "CORCHETE_CIERRA",
  "COMILLA",
  "TI",
  "TD",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "NUMERO",
  "FONT_FAMILY",
  "ALINEACION",
  "SIZE",
  "ABRE_C_H1",
  "CIERRA_C_H1",
  "ABRE_C_SPAM",
  "CIERRA_C_SPAM",
  "ABRE_C_P",
  "CIERRA_C_P",
  "ABRE_INPUT",
  "CIERRA_INPUT",
  "ABRE_TEXT_AREA",
  "CIERRA_TEXT_AREA"
  };
}

